### ISSUE TITLE
ENH: Different ways of differentiating

### ISSUE THREAD

**Issue by Gui-FernandesBR** [RocketPy-Team/RocketPy#131]
We need to improve the Function.differentiate method. As we know, its implementation is not ready for production and should be enhanced

See #122 as an example of where it is mentioned

**Comment by giovaniceotto** [comment]
Suggestions:

- Complex step differentiation
  - [Reference 1](https://mdolab.engin.umich.edu/wiki/guide-complex-step-derivative-approximation)
  - [Reference 2](https://blogs.mathworks.com/cleve/2013/10/14/complex-step-differentiation/)
- Automatic differentiation
  - [Reference 1](https://en.wikipedia.org/wiki/Automatic_differentiation)
  - [Reference 2](https://towardsdatascience.com/build-your-own-automatic-differentiation-program-6ecd585eec2a)
- Finite differences schemes as a fall back (let the user specify the order)
  - [Reference 1](https://web.media.mit.edu/~crtaylor/calculator.html)
