### ISSUE TITLE
Environment Analysis finishing touches

### ISSUE THREAD

**Issue by MateusStano** [RocketPy-Team/RocketPy#201]
**Environment Analysis** class is now on Master but it is still missing a few important features to be fully done:

- [x] Create a test_environment_class.py file and add tests for all of the class's features
- [x] Allow conversion of an Environment Analysis object to an Environment object, so that the data treatment made in the Environment Analysis can be used in a Flight simulation
- [x] Optimize code and speed
- [ ] Check if we can aggregate both surface and pressure level data from environment analysis into a flight simulation
- [ ] Automate data input by using OpenDap protocol (check if it is possible with Reanalysis).

Please be aware that some of tasks were already solved on one of our milestones!  https://github.com/RocketPy-Team/RocketPy/milestone/7?closed=1

**Comment by Gui-FernandesBR** [comment]
I am commenting the last two tasks from the list above:

>  - [ ] Check if we can aggregate both surface and pressure level data from environment analysis into a flight simulation

So, I tried to create this kind of comparison, but the thing is that there isn't too much to be compared from the "surface level dataset". It would be possible comparing only the wind speed between 10m and 100m of altitude. You can see my last trial here (do not seem to be good enough): 
![image](https://github.com/RocketPy-Team/RocketPy/assets/63590233/1f8f04fb-f7e1-422d-8df7-da161dac9cb4)

The only thing that we could still do is the compare the values of pressure, temperature and wind (speed and direction) at the surface level, which I strongly believe that won't be useful to anyone. For example: 
- temperature at surface level (based on surface file): 25 degC,
- temperature at surface level (based on pressure file): 28 degC,


>  - [ ] Automate data input by using OpenDap protocol (check if it is possible with Reanalysis).

Unfortunately, I don't think we should do it. There's an API provided by the Copernicus project [cdsapi](https://pypi.org/project/cdsapi/), but as anyone can see, this would require an API key, wich do not help. I didn't find any other way. 

Nevertheless, those env_analysis.nc files don't need to be downloaded too often, so I don't see any problem. **A better idea may be the creation of a quick tutorial on how to download and prepare the data to be inputted in the EnvironmentAnalysis class**, but that is totally secondary.

-------------------------------------------------------------------------------------------------------
With all that being said, I think we can close this issue after merging #373 , meaning that the last two suggested tasks suggested in this issue are no long valid.

I'm open to discuss it anyway :)
