### ISSUE TITLE
Docs: Broken links and images

### ISSUE THREAD

**Issue by giovaniceotto** [RocketPy-Team/RocketPy#204]
**Describe the bug**

The current start page of our documentation, which is pretty much are ReadMe, contains broken links and images.

**To Reproduce**

Navigate to https://docs.rocketpy.org/en/latest/ and scroll down until Supporting RocketPy and Contributing or Authors and Contributors. You will notice broken links and images, as shown below.

**Expected behavior**

No broken links or images!

**Screenshots**

![image](https://user-images.githubusercontent.com/572483/181406478-de944077-bcda-4eb0-b427-2483a6c4c00f.png)

![image](https://user-images.githubusercontent.com/572483/181406518-02e453fa-9034-48c1-b69d-7a6e6605a0ba.png)

**Additional context**

This may be caused by the conversion our ReadMe from Markdown to ReStructuredText, by the m2r2 package.

**Comment by Gui-FernandesBR** [comment]
Images restored, everything is working ok now, good way to start 2023 :)


![image](https://user-images.githubusercontent.com/63590233/210188376-3f32fc7e-d833-4adc-a87a-e9df5b72128a.png)

![image](https://user-images.githubusercontent.com/63590233/210188381-6419607b-6de4-4d94-8255-8be2c349ceeb.png)
