### ISSUE TITLE
Indefinite Integrals for Function objects

### ISSUE THREAD

**Issue by giovaniceotto** [RocketPy-Team/RocketPy#241]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

Indefinite Integrals for Function objects

**Comment by Gui-FernandesBR** [comment]
Please describe where/when this could be useful

**Comment by Gui-FernandesBR** [comment]
Maybe the new `Function.integral_function()` method already addressed this issue.
Needs confirmation.

**Comment by Gui-FernandesBR** [comment]
Confirmed by @giovaniceotto that it was solved by `enh/liquid-motors` development
