### ISSUE TITLE
SyntaxError: current version fails to run on Python releases earlier than 3.8

### ISSUE THREAD

**Issue by MrGribel** [RocketPy-Team/RocketPy#261]
**Describe the bug**
When importing the rocketpy module on python versions earlier than 3.8, a syntax error occurs due to a unpacking operator present in a return statement (a feature introduced recently) in the EnvironmentAnalysis class. 

**To Reproduce**

Try running the current PyPI rocketpy version on any python versions earlier than 3.8.

**Expected behavior**

Package initialization should be successful on all python versions described on the requirements docs (3.6+), or requirements should be changed.

**Screenshots**

![image](https://user-images.githubusercontent.com/54652318/197346380-7168846e-6251-4687-99c4-fc85b15cd000.png)

**Additional context**

Google Colab online environment defaults to Python version 3.7, so this issue breaks all the current online RocketPy Jupyter notebooks. This requires the user to run on an older version (before the merge of EnvironmentAnalysis), or update their Colab kernel with a more recent python version.

**Comment by Gui-FernandesBR** [comment]
By "current version", understand v0.12.0 (https://pypi.org/project/rocketpy/0.12.0/).

This issue was introduced on v0.11.0, which means that the newest version that is not dependent of python 3.8 is the 0.10.0 (https://pypi.org/project/rocketpy/0.10.0/)

**Comment by Gui-FernandesBR** [comment]
Solved!

![image](https://user-images.githubusercontent.com/63590233/197426860-65ffb952-040d-4386-85c9-7c3b961bd22b.png)
