### ISSUE TITLE
ENH: Create aerodynamic_surfaces parent class

### ISSUE THREAD

**Issue by Gui-FernandesBR** [RocketPy-Team/RocketPy#266]
**Is your feature request related to a problem? Please describe.**

Create a new class to handle all the aerodynamic (drag and lift) operations on rocketpy, saving some codeline of rocket class and starting 

**Describe the solution you'd like**

- [x] Create the aerodynamic_surface abstract class
- [ ] Use setters and getters to allow changes to aerodynamic surface definition parameters (for optimization and control)
- [ ] Move the Prandtl–Glauert transformation (beta) to the aerodynamic_surface abstract class
- [x] Create unit tests
- [ ] Move Drag Coefficients definition from the rocket class to the new aerodynamic_surfaces class
- [x] Fix legend on plots created by draw() methods
- [x] Plot airfoil information when it's available (#144 )
- [ ] Remove the addTail, addNose, addFins and similar methods from the rocket class

**Comment by giovaniceotto** [comment]
Closed by #342
