### ISSUE TITLE
ENH: Exponential backoff retry strategy 

### ISSUE THREAD

**Issue by Gui-FernandesBR** [RocketPy-Team/RocketPy#449]
**Is your feature request related to a problem? Please describe.**

Currently the Environment class practices a bad retry by iterating inside a while loop to catch API response within a certain number of maximum attempts. This can be problematic because the user can get blocked by the server or the API may not have enough time to process the new request after . A good standard is to apply exponential backoff, meaning that the execution will give longer pauses as the number of attempts increases.

* Dedicated python libraries may be considered. I'm leaving here two alternatives: https://pypi.org/project/backoff/ and https://stackoverflow.com/a/35636367/19971645
* I'm not against being a bit more verbose with those API recalls. I'd like to know what is happening when trying to retrieve data from te different APIs
* Implementing such features would let the code safer and more reliable.
* I found 6 occurrences of such problem within the Environment class.

**Additional context**

- To read more about [exponential backoff](https://en.wikipedia.org/wiki/Exponential_backoff#:~:text=An%20exponential%20backoff%20algorithm%20is,later%2C%20then%204%2C%20etc.)
- Example of problematic code lines: 
![image](https://github.com/RocketPy-Team/RocketPy/assets/63590233/71a78244-eef2-494c-b7b2-855ce3cbf860)

**Comment by Gui-FernandesBR** [comment]
I see two options for us:

1.  Start using a dedicated library to apply backoff retry in our requests
    - This is good because it let the code more compact, which is usually better for reading the code and also maintenance.
    - A very good library that could be used is: https://github.com/litl/backoff
2. Do the backoff by using for loops, in a pure python implementation
    - This might require more code line from us.
    - This doesn't generate a new dependency so it is easier to debug in case of things go wrong, but yet the code is larger. 

Further discussions are welcome here.

**Comment by lucasfourier** [comment]
I was messing around with some tests in the environment class and i think the best option might be to just use some custom Python code. For instance, consider this integration test:

![image](https://github.com/RocketPy-Team/RocketPy/assets/69172945/0f34fe06-9c55-467b-98b8-d36b9718dbec)

Maybe one could substitute 'time.sleep(1)' by 'time.sleep(i)' or 'time.sleep(2*i)', which would result in a linear backoff retry strategy and could possibly work.

Is that too naive? It was however the first thing that came to my mind.

**Comment by lucasfourier** [comment]
@Gui-FernandesBR What do you think?

**Comment by Gui-FernandesBR** [comment]
> I was messing around with some tests in the environment class and i think the best option might be to just use some custom Python code. For instance, consider this integration test:
> 
> ![image](https://private-user-images.githubusercontent.com/69172945/312650639-0f34fe06-9c55-467b-98b8-d36b9718dbec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NDMyODcsIm5iZiI6MTcxMzU0Mjk4NywicGF0aCI6Ii82OTE3Mjk0NS8zMTI2NTA2MzktMGYzNGZlMDYtOWM1NS00NjdiLTk4YjgtZDM2Yjk3MThkYmVjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDE2MDk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2ZmVjODY2MTYzNDY5MThjMWNkMzg4ODc0MTIyYmI5YTczNGQ1N2RiMzIyMDRhYjNhNGEwNmM3NjZjNzY4NzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.54UyayN5GmnMJx1QfYFf-oxGIncPq9E7-cYrtsVZ4PQ)
> 
> Maybe one could substitute 'time.sleep(1)' by 'time.sleep(i)' or 'time.sleep(2*i)', which would result in a linear backoff retry strategy and could possibly work.
> 
> Is that too naive? It was however the first thing that came to my mind.

This suggestion is good but only solves the tests functions. The requested solution was to deal with the exponential backoff directly inside the Environment class.

I proposed a solution in the last PR, #588
