### ISSUE TITLE
BUG: Motor.export_eng doesn't work for liquid motors

### ISSUE THREAD

**Issue by Gui-FernandesBR** [RocketPy-Team/RocketPy#473]
**Describe the bug**

Take a look the method's definition.
As the liquid motors do not have propellant grains, this method will fail. 

**To Reproduce**

Create a liquid motor and try to export its data using `export_eng` method

**Expected behavior**

- We should refactor this method and ensure that it work for 
- We should also create unit tests to prevent this behavior to happen again (please include all the types of motor in this test, even the GenericMotor)

**Screenshots**

![image](https://github.com/RocketPy-Team/RocketPy/assets/63590233/8e264938-351b-434a-9d1d-8c26ff5555dd)

**Comment by lucasfourier** [comment]
Working on it right now
