### ISSUE TITLE
ENH: Support for power series nose cones

### ISSUE THREAD

**Issue by Gui-FernandesBR** [RocketPy-Team/RocketPy#475]
**Is your feature request related to a problem? Please describe.**

The current supported nosecone kinds are: conical, ogive, lvhaack, tangent, vonkarman, elliptical, parabolic. The parabolic shape is just one particular case of the power series, see https://en.wikipedia.org/wiki/Nose_cone_design for more details.

**Describe the solution you'd like**

Support for power series nosecones. 

**Additional context**

Feature request from discord.
![image](https://github.com/RocketPy-Team/RocketPy/assets/63590233/b31b4d03-efd5-431b-9be8-0d22d93f6c15)

**Comment by lucasfourier** [comment]
Gonna try this one
