### ISSUE TITLE
DOC: duplicated github button on docs page

### ISSUE THREAD

**Issue by aureliobarbosa** [RocketPy-Team/RocketPy#723]
**Describe the bug**

The GitHub badge appearing on the right top badge menu of the documentation (just on the side of the Light/Dark, Linkedin, and PyPI badges) is duplicated.

**To Reproduce**

This 'bug' is appearing on the latest documentation documentation page, which at this  time corresponds to version 1.6.1.

**Expected behavior**

Just one badge should be present.

**Screenshots**
![image](https://github.com/user-attachments/assets/3468f55e-2bf8-47ad-b0df-3f0d1938e217)

**Additional context**

Do not apply.

**Comment by Gui-FernandesBR** [comment]
Thank you for opening this issue.
We are aware of such problem and the next minor version should already fix that, we plan to release it later this week.
#722

**Comment by aureliobarbosa** [comment]
Thanks for answering quickly, I was planning to fix it. Shouldn't mark as closed or mention it on the PR that closes the issue?

**Comment by Gui-FernandesBR** [comment]
> Thanks for answering quickly, I was planning to fix it. Shouldn't it be marked as closed or be mentioned on the PR that closes the issue?

Thanks for helping.
I will close this issue as soon as we merge #722 onto master.
